core/urls.py
from django.conf.urls import url
from . import views

app_name = 'core'

urlpatterns = [
    url(r'^$', views.homeview, name='home'),

	url(r'^signup$', views.user_signup, name="user_signup"),
    url(r'^login$', views.session_login, name="session_login"),
    url(r'^logout$', views.session_logout, name="session_logout"),

   	url(r'^user/dashboard$', views.user_dashboard, name='user_dashboard'),
    url(r'^user/profile$', views.user_profile, name="user_profile"),
    # url(r'^user/questionnaire$', views.user_questionaire, name="user_questionnaire")

]

echoproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from core import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^', include('questionnaire.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    type_choices = (
        ('AM', 'Admin'),
        ('CM', 'Client'),
        ('PM', 'Panel'),
        ('DM', 'Dietician'),
    )
    user_type = models.CharField(max_length=2,
                                 choices=type_choices,
                                 default='CM')

class Dietician(models.Model):
    user_name = models.OneToOneField('CustomUser', verbose_name="Name")
    qualification = models.CharField(max_length=1000)
    address = models.CharField(null=True, max_length=10000)

    class Meta:
        verbose_name = "Dietician"

    def __str__(self):
        return self.user_name.username

class Client(models.Model):
    user_name = models.OneToOneField('CustomUser')
    dietician = models.ForeignKey(Dietician)
    age = models.IntegerField(blank=True, null=True)
    height = models.IntegerField(blank=True, null=True)
    weight = models.IntegerField(blank=True, null=True)
    description = models.CharField(max_length=1000, null=True, blank=True)
    address = models.CharField(max_length=1000,blank=True, null=True)
    about_me = models.TextField(max_length=10000,blank=True, null=True)

    class Meta:
        verbose_name = 'Client'

    def __str__(self):
        return self.user_name.username

class Panel(models.Model):
    type_choices = (
        ('DO', 'Doctor'),
        ('NE', 'Neuropath'),
    )
    user_name = models.OneToOneField('CustomUser', verbose_name="Name")
    panel_type = models.CharField(max_length=2, choices=type_choices, default='DO')
    qualification = models.CharField(max_length=1000)
    address = models.CharField(null=True, max_length=10000)

    class Meta:
        verbose_name = "Panel"

    def __str__(self):
        return self.user_name.username

class Testimonial(models.Model):
    testiment_name = models.CharField(max_length=100)
    body = models.TextField()
    image = models.FileField()

    def __str__(self):
        return self.testiment_name

class Video(models.Model):
    video_name = models.CharField(max_length=1000)
    url = models.CharField(max_length=10000000)

    class Meta:
        verbose_name = "Video"
        verbose_name_plural = "Video"

    def __str__(self):
        return self.video_name

class TopAdBar(models.Model):
    ad_text = models.CharField(max_length=1000)
    url = models.CharField(max_length=10000)
    order = models.PositiveIntegerField()

    class Meta:
        verbose_name="Ad Bar Section"
        verbose_name_plural= "Ad Bar Section"

    def __str__(self):
        return self.ad_text

class SocialNetwork(models.Model):
    social_platform = models.CharField(max_length=100)
    url = models.CharField(max_length=1000)
    order = models.PositiveIntegerField()
    img = models.FileField(null=True, blank=True)

    class Meta:
        verbose_name = 'Social Network'
        verbose_name_plural = "Social Networks"

    def __str__(self):
        return self.social_platform


class Banner(models.Model):
    banner_name = models.CharField(max_length = 1000)

    banner_class = models.CharField(max_length=100, blank=True, null = True)

    package1_id = models.CharField(max_length=100, verbose_name="Technical stuff (to be used by developers", null = True, blank=True)
    package1_name = models.CharField(max_length=1000)
    package1_url = models.CharField(max_length=10000, blank=True, null=True)
    package1_img = models.FileField()

    package2_id = models.CharField(max_length=100, verbose_name="Technical stuff (to be used by developers", null = True, blank=True)
    package2_name = models.CharField(max_length=1000)
    package2_url = models.CharField(max_length=10000, blank=True, null=True)
    package2_img = models.FileField()

    package3_id = models.CharField(max_length=100, verbose_name="Technical stuff (to be used by developers", null = True, blank=True)
    package3_name = models.CharField(max_length=1000)
    package3_url = models.CharField(max_length=10000, blank=True, null=True)    
    package3_img = models.FileField()

    package4_id = models.CharField(max_length=100, verbose_name="Technical stuff (to be used by developers", null = True, blank=True)
    package4_name = models.CharField(max_length=1000)
    package4_url = models.CharField(max_length=10000, blank=True, null=True)    
    package4_img = models.FileField()

    banner_tagline = models.CharField(max_length=1000)

    order = models.PositiveIntegerField()

    class Meta:
        verbose_name = "Banner Package"
        verbose_name_plural = "Banner Packages"

    def __str__(self):
        return self.banner_name

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from core.models import *
from notification.models import Notification
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, Http404
from django.views.decorators.http import condition


def homeview(request):
	testimonial_list = Testimonial.objects.all()
	video_list = Video.objects.all()
	ad_list = TopAdBar.objects.order_by('order')
	banner_list = Banner.objects.order_by('order')
	context = {
		'testimonial_list' : testimonial_list,
		'video_list': video_list,
		'ad_list': ad_list,
		'banner_list': banner_list}
	return render(request, "home/home.html", context)

def user_signup(request):
	context = {}
	return render(request, "after_login/user/user_signup.html", context)

def session_login(request):
	if not request.user.is_authenticated:
		if request.method == 'POST':
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)

			if user is not None:
				if user.user_type == 'CM':
					login(request, user)
					return redirect('core:user_dashboard')
				elif user.user_type == 'DM':
					login(request, user)
					return HttpResponse('dietician panel')
				elif user.user_type == 'PM':
					login(request, user)
					return HttpResponse('docters and neuropath module')
				else:
					return HttpResponse('You have a separate admin panel login there!')		
			else:
				return render(request, 'after_login/login.html', {'error_message': 'Invalid Login Credentials'})
		return render(request, 'after_login/login.html')
	else:
		if request.user.user_type == 'CM':
			return redirect('core:user_dashboard')
		elif request.user.user_type == 'DM':
			return HttpResponse('dietician panel')
		elif request.user.user_type == 'PM':
			return HttpResponse('docters and neuropath module')
		else:
			return HttpResponse('You have a separate admin panel login there!')

@login_required(login_url="core:session_login")
def session_logout(request):
	logout(request)
	return redirect('core:home')

@login_required(login_url="core:session_login")
@user_passes_test(lambda u: u.user_type=='CM', redirect_field_name='/login')
def user_dashboard(request):
	notification_list = Notification.objects.filter(notification_for=request.user, viewed=False).order_by('-created_at')[:40]
	context = {
		'notification_list' : notification_list,
		'notification_count' : notification_list.count(),
		}
	return render(request, "after_login/user/user_dashboard.html", context)

@login_required(login_url="core:session_login")
@user_passes_test(lambda u: u.user_type=='CM', redirect_field_name='/login')
def user_profile(request):
	context = {}
	return render(request, "after_login/user/user_profile.html", context)

core/templates/after_login/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="apple-touch-icon" sizes="76x76" href="static/img/apple-icon.png">
    <link rel="icon" type="image/png" sizes="96x96" href="static/img/favicon.png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>{% block pagetitle %}Echo India{% endblock %}</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

    {% load static %}
    <!-- Bootstrap core CSS     -->
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet" />

    <!-- Animation library for notifications   -->
    <link href="{% static 'core/css/animate.min.css' %}" rel="stylesheet"/>

    <!--  Paper Dashboard core CSS    -->
    <link href="{% static 'core/css/paper-dashboard.css' %}" rel="stylesheet"/>


    <!--  CSS for Demo Purpose, don't include it in your project     -->
    <link href="{% static 'core/css/demo.css' %}" rel="stylesheet" />


    <!--  Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'core/css/themify-icons.css' %}" rel="stylesheet">
    {% block style %}{% endblock %}
</head>
<body>

{% block body %}
<div class="wrapper">
    <div class="sidebar" data-background-color="white" data-active-color="danger">

    <!--
        Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
        Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
    -->

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    Echo India
                </a>
            </div>

            <ul class="nav">
                <li {% if request.path == "/user/dashboard" %}class="active"{% endif %}>
                    <a href="{% url 'core:user_dashboard' %}">
                        <i class="ti-dashboard"></i>
                        <p>My Dashboard</p>
                    </a>
                </li>
                <li {% if request.path == "/user/profile" %}class="active"{% endif %}>
                    <a href="{% url 'core:user_profile' %}">
                        <i class="ti-user"></i>
                        <p>My Profile</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'core:session_logout' %}">
                        <i class="ti-power-off"></i> 
                        <p>Log Out</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'core:user_dashboard' %}">My {% block title %}Dashboard{% endblock %}</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="{% url 'core:user_profile' %}">
                                <i class="ti-user"></i>
                                <p>Welcome, {{ user.username }}</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-bell"></i>
                                    <p class="notification">{{ updates_count }}</p>
                                    <p>Updates</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                {% for update in updates_list %}
                                    {% if request.user == update.update_for %}
                                        <li><a href="#">{{ update.details }}</a></li>
                                    {% endif %}
                                {% endfor %}
                              </ul>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-announcement"></i>
                                    <p class="notification">{{ notification_count }}</p>
                                    <p>Notifications</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                {% for notification in notification_list %}
                                    <li><a href="#">{{ notification.title }}</a></li>
                                {% empty %}
                                    <li><a href="#">No Notifications</a></li>
                                {% endfor %}
                              </ul>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>


        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
         
        <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>

                        <li>
                            <a href="#">
                                Echo India
                            </a>
                        </li>
                        <li>
                            <a href="http://blog.creative-tim.com">
                               Blog
                            </a>
                        </li>
                        <li>
                            <a href="http://www.creative-tim.com/license">
                                Licenses
                            </a>
                        </li>
                    </ul>
                </nav>
                <div class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script>, made with <i class="fa fa-heart heart"></i> by <a href="http://www.creative-tim.com">Echo India</a>
                </div>
            </div>
        </footer>

    </div>
</div>

{% endblock %}


</body>

    <!--   Core JS Files   -->
    <script src="{% static 'core/js/jquery-1.10.2.js' %}" type="text/javascript"></script>
    <script src="{% static 'core/js/bootstrap.min.js' %}" type="text/javascript"></script>

    <!--  Checkbox, Radio & Switch Plugins -->
    <script src="{% static 'core/js/bootstrap-checkbox-radio.js' %}"></script>

    <!--  Charts Plugin -->
    <script src="{% static 'core/js/' %}chartist.min.js"></script>

    <!--  Notifications Plugin    -->
    <script src="{% static 'core/js/' %}bootstrap-notify.js"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

    <!-- Paper Dashboard Core javascript and methods for Demo purpose -->
    <script src="{% static 'core/js/' %}paper-dashboard.js"></script>

    <!-- Paper Dashboard DEMO methods, don't include it in your project! -->
    <script src="{% static 'core/js/' %}demo.js"></script>
    
    {% block script %}

    {% endblock %}

</html>

core/templates/after_login/login.html
{% extends 'after_login/base.html' %}

{% block pagetitle %}
    User Login
{% endblock %}

{% block style %}
<style>
    body, html{
        height: 100%;
        background-color: #f4f3ef;
    }
    .poora{
        height: 100%;
    }
    
    .bichmein{
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
    }
</style>
{% endblock %}

{% block script %}
{% endblock %}

{% block body %}

<div class="content poora">
    <div class="container-fluid poora">
        <div class="row poora">
                    <div class="col-md-4 bichmein">
                        <div class="card ">
                            <div class="header">
                                <h4 class="title text-center">Users Module | Sign In</h4>
                                <hr>
                            </div>
                            <div class="content">
                                    {% if error_message %}
                                        <p><strong>{{ error_message }}</strong></p>
                                    {% endif %}
                                    <form action="{% url 'core:session_login' %}" method="post">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="username">Username: </label>
                                            <input type="text" name='username' placeholder="Username" class="form-control border-input"/>
                                            <label for="password">Password: </label>
                                            <input type="password" name='password' placeholder="Password" class="form-control border-input"/>
                                        </div>
                                        <button type="submit" class="btn btn-fill btn-success">Login</button>
                                    </form>
                            <div class="footer">
                                    <hr>
                                    <div class="stats">
                                        <!-- <p>New User? <a href="{% url 'core:user_signup' %}">Sign Up</a></p> -->
                                        <p>Forgotton Password? <a href="#">Click here</a></p>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock %}

core/templates/after_login/panel_login.html
{% extends 'core/base.html' %}

{% block title %}
    Panel Login
{% endblock %}

{% block style %}
<style>
    body, html{
        height: 100%;
        background-color: #f4f3ef;
    }
    .poora{
        height: 100%;
    }
    
    .bichmein{
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
    }
</style>
{% endblock %}

{% block script %}
{% endblock %}

{% block body %}

<div class="content poora">
    <div class="container-fluid poora">
        <div class="row poora">
                    <div class="col-md-4 bichmein">
                        <div class="card ">
                            <div class="header">
                                <h4 class="title text-center">Panel Module | Sign In</h4>
                                <hr>
                            </div>
                            <div class="content">
                                    <form action="login">
                                        <div class="form-group">
                                            <label for="username">Username: </label>
                                            <input type="text" placeholder="Username" class="form-control border-input"/>
                                            <label for="password">Password: </label>
                                            <input type="password" placeholder="Password" class="form-control border-input"/>
                                        </div>
                                        <button type="submit" class="btn btn-fill btn-success">Login</button>
                                    </form>
                            <div class="footer">
                                    <hr>
                                    <div class="stats">
                                        <!-- <p>New User? <a href="#">Sign Up</a></p> -->
                                        <p>Forgotton Password? <a href="#">Click here</a></p>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>
{% endblock %}